In [1]:
import numpy

a = numpy.matrix(numpy.random.randint(1, 10, size=(3, 3)))
b = numpy.matrix(numpy.random.randint(1, 10, size=(3, 2)))
print(a)
print(b)
print(a*b)

[[9 6 8]
 [2 1 6]
 [7 8 6]]
[[6 1]
 [2 3]
 [2 1]]
[[82 35]
 [26 11]
 [70 37]]


In [1]:
from function_sets import function_sets
func_sets = function_sets()
print(func_sets.sigma(0))

0.5
