In [7]:
import numpy

a = numpy.matrix(numpy.random.randint(1, 10, size=(3, 3)))
b = numpy.matrix(numpy.random.randint(1, 10, size=(3, 2)))
print(a)
print(b)
print(a*b)

[[8 6 2]
 [4 1 9]
 [8 2 2]]
[[5 3]
 [1 4]
 [2 9]]
[[50 66]
 [39 97]
 [46 50]]
